FROM golang:1.19 as build-stage
RUN apt-get install tzdata
WORKDIR /app
COPY scraper/go.mod scraper/go.sum ./
RUN go mod download
COPY scraper/*.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /scraper

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM alpine:3.19 AS build-release-stage
WORKDIR /
RUN apk --update --no-cache add curl
COPY --from=build-stage /usr/share/zoneinfo/Asia /usr/share/zoneinfo/Asia
COPY --from=build-stage /scraper /scraper
EXPOSE 80
ENTRYPOINT ["/scraper"]